# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'RollsAuth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RollsAuth
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'SnapKit', '5.6.0'
  pod 'SwiftLint'

end
